# file paths are relative to the .devcontainers directory
# even though the docker-compose command may be run
# from the repo root.
version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.bash_aliases:/home/vscode/.bash_aliases
      - ../..:/workspaces:cached
    environment:
      - TZ=America/Los_Angeles
    command: "-c 'sleep infinity'"
    restart: unless-stopped
    logging:
      driver: syslog
    # Required for ptrace-based debuggers like C++, Go, and Rust
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

  db:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    logging:
      driver: syslog

  # try out cockroach db: https://github.com/cockroachdb/cockroach/issues/107416#issuecomment-1648127261

  db-admin:
    image: dpage/pgadmin4:8.3
    env_file: .env
    restart: unless-stopped
    logging:
      driver: syslog

  cache:
    image: redis:alpine
    command: [ "redis-server", "--requirepass", "9JXZW7W3hznCg8dR" ]
    restart: unless-stopped
    logging:
      driver: syslog

volumes:
  pg_data:
  cdb_data:
