# file paths are relative to the .devcontainers directory
# even though the docker-compose command may be run
# from the repo root.
version: "3.3"

services:

  dev:
    container_name: gops-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.bash_aliases:/home/vscode/.bash_aliases
      - ../:/home/vscode/ws
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Los_Angeles
    command: "-c 'sleep infinity'"
    restart: unless-stopped
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  db:
    hostname: db-dev
    container_name: gops-dev-db
    image: postgres:12.12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: archive_db
      POSTGRES_PASSWORD: "4khyw"
    restart: unless-stopped

  db-admin:
    container_name: gops-dev-db-admin
    image: dpage/pgadmin4:6.19
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@gops.dev.com
      PGADMIN_DEFAULT_PASSWORD: 6et3l32qLwEGlIb9HsNjJ14nSZEALLhVBIwu1L3eGWw

    restart: unless-stopped
    ports:
      - "5051:80"

  cache:
    hostname: cache-dev
    container_name: gops-dev-cache
    image: redis:alpine
    command: [ "redis-server", "--requirepass", "9JXZW7W3hznCg8dR" ]
    restart: unless-stopped

volumes:
  pg_data:
